version: '3.8'

volumes:
    logs:
        driver: local

services:
    web:
      build: .
      container_name: my_ping_backend
      image: php:7.0-apache
      working_dir: /var/www/html
      command: php -S 0.0.0.0:80 -t /var/www/html
      environment:
          docker: "true"
      ports:
          - "80:80"
      stdin_open: true
